version: '3.7'
services:
  appointments-db-autotest:
    container_name: appointments-db-autotest
    image: mongo:4.4.4
    command: mongod
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
