version: '3.7'
services:
  db-autotest:
    container_name: db-autotest
    image: mongo:4.4.4
    command: mongod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
